#!/bin/bash
# . "$HOME/anaconda3/etc/profile.d/conda.sh"
eval "$(conda shell.bash hook)"
conda activate my_tf
source ~/mitali/scripts/setup_gpu_limit.sh $1%
# max colocation 1, mem req = 3454MB

# number of processes co-located = $2
cmd="python3 ~/mitali/distillbert-imdb/main_googleT5_pytorch.py --batch-size 32 >/dev/null 2>&1 &"
#  >/dev/null 2>&1
final_cmd=''
for((c=1;c<=$2;c++))
do
    final_cmd="$final_cmd $cmd"
done

start=$(date +%s.%3N)
eval $final_cmd
wait
end=$(date +%s.%3N)
runtime=$(echo $end $start | awk '{print $1 - $2}')
echo $runtime
