#!/bin/bash
eval "$(conda shell.bash hook)"
conda activate tf
TIMEFORMAT=%R
# Colocated functions = 1
# start=$(date +%s%N)
# source ~/pramod/set_gpu_limits.sh '0=16G' 100%
# time python3 /home/ub-11/pramod/image_recognition/resnet_bursty.py --batch-size 150 &

# Colocated functions = 2
source ~/pramod/set_gpu_limits.sh '0=8G' 50%
python3 /home/ub-11/pramod/image_recognition/resnet_bursty.py --batch-size 150 &
# python3 /home/ub-11/pramod/image_recognition/resnet_bursty.py --batch-size 150 &

# Colocated functions = 3
# source ~/pramod/set_gpu_limits.sh '0=5G' 33%
# python3 /home/ub-11/pramod/image_recognition/resnet_bursty.py --batch-size 350 --total-images 20000 &
# python3 /home/ub-11/pramod/image_recognition/resnet_bursty.py --batch-size 350 --total-images 20000 &
# python3 /home/ub-11/pramod/image_recognition/resnet_bursty.py --batch-size 350 --total-images 20000 &

# Colocated functions = 4
# source ~/pramod/set_gpu_limits.sh '0=4G' 25%
# python3 /home/ub-11/pramod/image_recognition/resnet_bursty.py --batch-size 220 --total-images 20000 &
# python3 /home/ub-11/pramod/image_recognition/resnet_bursty.py --batch-size 220 --total-images 20000 &
# python3 /home/ub-11/pramod/image_recognition/resnet_bursty.py --batch-size 220 --total-images 20000 &
# python3 /home/ub-11/pramod/image_recognition/resnet_bursty.py --batch-size 220 --total-images 20000 &
wait
# end=$(date +%s%N)
# echo "Elapsed time: $(($(($end-$start))/1000000000)) s"