#!/bin/bash
eval "$(conda shell.bash hook)"
conda activate my_tf
# source ~/pramod/set_gpu_limits.sh '0=4G' 33
home="/home/ub-11/mitali/FuxiCTR/model_zoo"
cd $home/DCN/DCN_torch && python run_expid.py --expid DCN_test --gpu 0 && cd /home/ub-11/mitali/workload_executables